openapi: 3.0.0
info:
  title: API de Películas
  description: API REST para gestionar películas usando Node.js, Express y MySQL
  version: 1.0.0

servers:
  - url: http://localhost:3000/api

paths:
  /peliculas:
    get:
      summary: Obtener todas las películas
      responses:
        '200':
          description: Lista de películas
    post:
      summary: Insertar una nueva película
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - titulo
                - director
                - genero
                - anio
              properties:
                titulo:
                  type: string
                director:
                  type: string
                genero:
                  type: string
                anio:
                  type: integer
                descripcion:
                  type: string
      responses:
        '200':
          description: Película agregada exitosamente

  /peliculas/{id}:
    delete:
      summary: Eliminar una película por ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID de la película
      responses:
        '200':
          description: Película eliminada
